yaml
name: Windows Build

on:
  workflow_dispatch: # Ermöglicht den manuellen Start über den "Run workflow" Button

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B build -G "Visual Studio 17 2022" -A x64

    - name: Build VST3
      run: cmake --build build --config Release

    - name: Upload VST3 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Vamos-VST3-Windows
        path: build/Release/Vamos_artefacts/VST3/
