on:
  workflow_dispatch: # Ermöglicht den manuellen Start über den "Run workflow" Button

name: Windows Build

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B build -G "Visual Studio 18 2026" -A x64

    - name: Build VST3
      run: cmake --build build --config Release --parallel 4

    - name: Locate VST3 Plugin
      id: locate
      shell: cmd
      run: |
        for /f "delims=" %%i in ('dir /b /s build\*_artefacts\VST3') do (
          echo VST3_PATH=%%i >> %GITHUB_ENV%)
          
    - name: Upload VST3 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Vamos-VST3-Windows
        path: ${{ env.VST3_PATH }}
